apiVersion: v1
kind: Namespace
metadata:
  name: unity-tool-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unity-tool-frontend
  namespace: unity-tool-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unity-tool-frontend
  template:
    metadata:
      labels:
        app: unity-tool-frontend
    spec:
      containers:
        - name: unity-tool-frontend
          image: ghcr.io/okane-no/unity-tool-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  name: unity-tool-frontend
  namespace: unity-tool-prod
spec:
  selector:
    app: unity-tool-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
# Canonical host: www.eventlinktounity.com
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unity-tool-frontend-www
  namespace: unity-tool-prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-certificate"
spec:
  ingressClassName: nginx
  rules:
    - host: www.eventlinktounity.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unity-tool-frontend
                port:
                  number: 80
  tls:
    - hosts:
        - www.eventlinktounity.com
      secretName: unity-tool-frontend-tls-www
---
# Redirect everything from apex → www BEFORE it hits the service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirect-apex-to-www
  namespace: unity-tool-prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-certificate"
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.eventlinktounity.com$request_uri
spec:
  ingressClassName: nginx
  rules:
    - host: eventlinktounity.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              # backend won't be reached due to redirect, but k8s requires one
              service:
                name: unity-tool-frontend
                port:
                  number: 80
  tls:
    - hosts:
        - eventlinktounity.com
      secretName: unity-tool-frontend-tls-apex
