apiVersion: v1
kind: Namespace
metadata:
  name: unity-tool-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unity-tool-frontend
  namespace: unity-tool-prod
spec:
  replicas: 2  # avoid cold starts
  selector:
    matchLabels:
      app: unity-tool-frontend
  template:
    metadata:
      labels:
        app: unity-tool-frontend
    spec:
      containers:
        - name: unity-tool-frontend
          image: ghcr.io/okane-no/unity-tool-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  name: unity-tool-frontend
  namespace: unity-tool-prod
spec:
  selector:
    app: unity-tool-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
# One cert for both hosts (SANs)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unity-tool-frontend-cert
  namespace: unity-tool-prod
spec:
  secretName: unity-tool-frontend-tls
  issuerRef:
    name: letsencrypt-certificate
    kind: ClusterIssuer
  dnsNames:
    - eventlinktounity.com
    - www.eventlinktounity.com
---
# Serve site on CANONICAL host: www.eventlinktounity.com
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unity-tool-frontend-www
  namespace: unity-tool-prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-certificate"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"   # http -> https
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.eventlinktounity.com
      secretName: unity-tool-frontend-tls
  rules:
    - host: www.eventlinktounity.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unity-tool-frontend
                port:
                  number: 80
---
# Redirect EVERYTHING from apex -> www (single immediate 308)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirect-apex-to-www
  namespace: unity-tool-prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-certificate"
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.eventlinktounity.com$request_uri
    nginx.ingress.kubernetes.io/permanent-redirect-code: "308"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - eventlinktounity.com
      secretName: unity-tool-frontend-tls   # reuse same cert
  rules:
    - host: eventlinktounity.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              # never reached; redirect happens at ingress
              service:
                name: unity-tool-frontend
                port:
                  number: 80
